//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bARBERsQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barber()
        {
            this.hISTORies = new HashSet<hISTORY>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<bool> Pol { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime DateBirthday { get; set; }
        public System.DateTime WorkStart { get; set; }
        public int PositionId { get; set; }
        public int ListUslugiId { get; set; }
        public int ListFeedBackId { get; set; }
    
        public virtual ListFeddbackCl ListFeddbackCl { get; set; }
        public virtual ListUsl ListUsl { get; set; }
        public virtual Poistion Poistion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hISTORY> hISTORies { get; set; }
    }
}
