//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bARBERsQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeddbackCl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeddbackCl()
        {
            this.ListFeddbackCls = new HashSet<ListFeddbackCl>();
        }
    
        public int Id { get; set; }
        public string Desciption { get; set; }
        public int ClientId { get; set; }
        public int Stars { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListFeddbackCl> ListFeddbackCls { get; set; }
    }
}
