//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bARBERsQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hISTORY
    {
        public int Id { get; set; }
        public int BarberId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> FeedbackIdCl { get; set; }
        public int ListUslId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<decimal> AllPrice { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Client Client { get; set; }
        public virtual ListFeddbackCl ListFeddbackCl { get; set; }
        public virtual ListUsl ListUsl { get; set; }
    }
}
