//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bARBERsQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities1 : DbContext
    {
        public Database1Entities1()
            : base("name=Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barber> Barbers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<FeddbackCl> FeddbackCls { get; set; }
        public virtual DbSet<hISTORY> hISTORies { get; set; }
        public virtual DbSet<ListFeddbackCl> ListFeddbackCls { get; set; }
        public virtual DbSet<ListUsl> ListUsls { get; set; }
        public virtual DbSet<Poistion> Poistions { get; set; }
        public virtual DbSet<Uslugi> Uslugis { get; set; }
    }
}
